import {chromium} from 'playwright';
import fs from 'node:fs/promises';
import {spawnSync} from 'node:child_process';
import {chapters,allCues} from '../src/content.ts';
import {scoreFor} from '../src/SoundScore.ts';
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--use-angle=d3d11']});
const context=await browser.newContext({viewport:{width:1920,height:1080}}),page=await context.newPage(),errors=[],results=[];
page.on('pageerror',e=>errors.push(e.message));
const check=(name,pass,details={})=>{results.push({name,pass,...details});console.log(pass?'PASS':'FAIL',name);};
const settle=()=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
const state=()=>page.evaluate(()=>window.deck.audio.state());
const go=async(s,b=0)=>{await page.evaluate(([s,b])=>window.deck.go(s,b),[s,b]);await settle();};
const seek=async t=>{await page.evaluate(t=>window.deck.seek(t),t);await settle();};
await fs.mkdir('qa/audio/renders',{recursive:true});await page.goto('http://127.0.0.1:5173/');await page.waitForFunction(()=>window.deck?.ready);
check('initial load has no audio context or automatic sound',(await state()).status==='locked'&&!(await state()).enabled);
await page.getByRole('button',{name:'เปิดเสียง',exact:true}).click();await page.waitForFunction(()=>window.deck.audio.state().status==='ready');
check('user gesture unlocks running local Web Audio',(await state()).enabled&&(await state()).context==='running');
check('effects-only and speech space are defaults',!(await state()).ambient&&(await state()).speechSafe);
await page.evaluate(()=>window.deck.pause());await page.waitForTimeout(120);check('pause clears audible and scheduled voices',(await state()).voices===0);
await go(5,2);await seek(4);await page.evaluate(()=>window.deck.resume());await go(5,3);await page.waitForTimeout(280);
check('navigation schedules the current camera journey',(await state()).playing&&(await state()).cue==='06.04'&&(await state()).voices>=2);
await page.evaluate(()=>window.deck.pause());await page.waitForTimeout(120);check('mid-flight pause releases all voices',(await state()).voices===0);
await seek(.95);await page.evaluate(()=>window.deck.resume());await page.waitForTimeout(120);check('resume reconstructs remaining sound without full replay',(await state()).playing&&(await state()).voices>0);
await seek(4);await page.waitForTimeout(120);check('reading hold is silent in effects-only mode',(await state()).voices===0);
await page.evaluate(()=>window.deck.audio.ambient(true));await page.waitForTimeout(180);check('optional place ambience uses one looping source',(await state()).voices===1);
await page.keyboard.press('b');await page.waitForTimeout(120);check('blackout silences ambience',(await state()).voices===0);
await page.keyboard.press('b');await page.waitForTimeout(150);check('unblank resumes current ambience',(await state()).voices===1);
await page.keyboard.press('m');await page.waitForTimeout(150);check('M mutes and releases audio',!(await state()).enabled&&(await state()).voices===0);
await page.keyboard.press('m');await page.waitForTimeout(150);check('M restores enabled sound',(await state()).enabled);
await page.evaluate(()=>window.deck.audio.volume(.32));await page.getByRole('button',{name:'ตั้งค่าเสียง'}).click();
check('volume UI reflects engine value',await page.getByRole('slider',{name:'ระดับเสียง'}).inputValue()==='32');
await page.getByRole('button',{name:'ทดสอบเสียง'}).click();await page.waitForTimeout(180);check('test sound does not need navigation',(await state()).voices>=1);
await page.getByRole('button',{name:'ปิดตั้งค่าเสียง'}).click();
await page.evaluate(()=>{window.deck.pause();window.deck.audio.volume(.65);window.deck.audio.ambient(false);});
const bounds=[];for(let i=0;i<18;i++){await page.evaluate(()=>window.deck.resume());await go(i%2?5:8,i%2?3:1);await page.waitForTimeout(30);bounds.push((await state()).voices);}
await page.waitForTimeout(180);check('rapid navigation keeps voices bounded',Math.max(...bounds)<=12,{maxVoices:Math.max(...bounds)});
await page.evaluate(()=>window.deck.audio.ambient(true));await page.waitForTimeout(3000);const ambientBounds=[];for(let i=0;i<20;i++){await go(i%2?5:8,i%2?3:1);await page.waitForTimeout(25);ambientBounds.push((await state()).voices);}check('rapid navigation with ambience does not extend cancelled tails',Math.max(...ambientBounds)<=12,{maxVoices:Math.max(...ambientBounds)});await page.evaluate(()=>window.deck.pause());await page.waitForTimeout(120);check('pause cuts all retiring ambience tails',(await state()).voices===0);
await page.evaluate(()=>window.deck.pause());await go(1,0);await seek(4);await page.evaluate(()=>{window.deck.audio.ambient(true);window.deck.resume();});await page.waitForTimeout(180);
check('game placeholder has no looping atmosphere',(await state()).voices===0);
await page.evaluate(()=>window.deck.pause());await go(5,3);await page.emulateMedia({reducedMotion:'reduce'});await settle();
let fullMotion=await page.evaluate(()=>window.deck.audio.render(4,true));await fs.writeFile('qa/audio/renders/full-motion.wav',Buffer.from(fullMotion.base64,'base64'));delete fullMotion.base64;
check('system motion preference retains camera travel sound',scoreFor(chapters[5].cues[3],{journey:true}).events.some(e=>e.role==='travel'),{render:fullMotion});
await page.emulateMedia({reducedMotion:'no-preference'});await seek(4);await page.evaluate(()=>window.deck.setFallback());
check('sound survives WebGL fallback',(await state()).status==='ready');
await page.evaluate(()=>window.deck.audio.ambient(false));
const renders=[];
for(const item of allCues){await go(item.scene,item.beat);const r=await page.evaluate(()=>window.deck.audio.render(4,false));await fs.writeFile(`qa/audio/renders/${item.cue.id}.wav`,Buffer.from(r.base64,'base64'));delete r.base64;renders.push({cue:item.cue.id,kind:item.cue.kind,...r});}
check('all 42 cue scores render through the production mix',renders.length===42&&renders.every(r=>r.sampleRate===48000&&r.channels===2&&r.peakDbFS<-10&&r.peakDbFS>-70),{worstPeakDbFS:Math.max(...renders.map(r=>r.peakDbFS))});
const clips=JSON.parse(await fs.readFile('qa/place-journey/render.json','utf8')).clips;
for(const clip of clips){await go(...clip.from);await seek(4);await go(...clip.to);const r=await page.evaluate(()=>window.deck.audio.render(4,true));await fs.writeFile(`qa/audio/${clip.name}.wav`,Buffer.from(r.base64,'base64'));}
await go(8,1);await page.evaluate(()=>window.deck.audio.ambient(true));const r=await page.evaluate(()=>window.deck.audio.render(24,true));await fs.writeFile('qa/audio/loop-listening.wav',Buffer.from(r.base64,'base64'));
const repeat=await page.evaluate(()=>window.deck.audio.render(24,true));await fs.writeFile('qa/audio/debug-repeat-full.wav',Buffer.from(repeat.base64,'base64'));const pcmA=Buffer.from(r.base64,'base64'),pcmB=Buffer.from(repeat.base64,'base64');let maxDelta=0,changed=0;for(let i=44;i<pcmA.length;i+=2){const d=Math.abs(pcmA.readInt16LE(i)-pcmB.readInt16LE(i));maxDelta=Math.max(maxDelta,d);changed+=d>0;}const changedPercent=changed/((pcmA.length-44)/2)*100;check('offline mix repeats within PCM rounding',maxDelta<=1&&changedPercent<=.1,{maxSampleDelta:maxDelta,changedSamples:changed,changedPercent,firstPeak:r.peakDbFS,secondPeak:repeat.peakDbFS,note:'Same timing and waveform; ≤1 PCM16 step in ≤0.1% of samples. First investigation found 1 step in 440/2304000 samples, with 0.00000181 dB peak difference.'});
await page.evaluate(()=>{window.deck.audio.ambient(false);window.deck.audio.speechSafe(false);});const full=await page.evaluate(()=>window.deck.audio.render(4,false));await fs.writeFile('qa/audio/carve-off.wav',Buffer.from(full.base64,'base64'));await page.evaluate(()=>window.deck.audio.speechSafe(true));const carved=await page.evaluate(()=>window.deck.audio.render(4,false));await fs.writeFile('qa/audio/carve-on.wav',Buffer.from(carved.base64,'base64'));
const presenter=await context.newPage();await presenter.addInitScript(()=>{window.__contextCount=0;const Native=window.AudioContext;window.AudioContext=class extends Native{constructor(...args){super(...args);window.__contextCount++;}};});await presenter.goto('http://127.0.0.1:5173/?presenter=1');await presenter.getByRole('button',{name:/คุมเสียงจอฉาย/}).click();
await presenter.getByRole('slider',{name:'ระดับเสียง'}).fill('41');await page.waitForTimeout(150);check('presenter volume controls the single stage audio engine',Math.abs((await state()).volume-.41)<.001);
await presenter.getByRole('button',{name:'ปิดเสียง · M'}).click();await page.waitForTimeout(150);check('presenter mute reaches stage',!(await state()).enabled);
check('presenter has no duplicate audio context',await presenter.evaluate(()=>window.__contextCount===0&&document.querySelectorAll('canvas').length===0));
await presenter.close();
await page.getByRole('button',{name:'ตั้งค่าเสียง'}).click();await page.screenshot({path:'qa/audio-controls.png'});
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'qa/audio-controls-mobile.png'});
check('mobile sound controls fit the viewport',await page.locator('.sound-panel').evaluate(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.bottom<=innerHeight;}));
const locked=await context.newPage();await locked.goto('http://127.0.0.1:5173/');await locked.waitForFunction(()=>window.deck?.ready);check('refresh stays locked while retaining volume preference',await locked.evaluate(()=>window.deck.audio.state().status==='locked'&&!window.deck.audio.state().enabled&&Math.abs(window.deck.audio.state().volume-.41)<.001));await locked.close();
// Delayed and missing sound assets must never block font/image readiness or navigation.
const slow=await context.newPage();await slow.route('**/assets/audio/*.wav',async route=>{await new Promise(r=>setTimeout(r,550));await route.continue();});await slow.goto('http://127.0.0.1:5173/');await slow.waitForFunction(()=>window.deck?.ready);await slow.getByRole('button',{name:'เปิดเสียง',exact:true}).click();await slow.keyboard.press('ArrowRight');check('slow audio loading leaves slide navigation responsive',await slow.evaluate(()=>window.deck.ready));await slow.waitForFunction(()=>window.deck.audio.state().status==='ready');await slow.close();
const missing=await context.newPage();await missing.route('**/assets/audio/glass.wav',route=>route.abort());await missing.goto('http://127.0.0.1:5173/');await missing.waitForFunction(()=>window.deck?.ready);await missing.getByRole('button',{name:'เปิดเสียง',exact:true}).click();await missing.waitForFunction(()=>window.deck.audio.state().status==='error');await missing.keyboard.press('ArrowRight');await missing.waitForTimeout(100);check('missing audio fails visibly without breaking slides',await missing.evaluate(()=>window.deck.ready&&!window.deck.audio.state().enabled&&window.deck.state().cue==='01.02')&&await missing.locator('.sound-panel').isVisible()&&(await missing.locator('.sound-help').textContent()).includes('ลองเปิดเสียงอีกครั้ง'));await missing.unroute('**/assets/audio/glass.wav');await missing.getByRole('button',{name:'เปิดเสียง · M'}).click();await missing.waitForFunction(()=>window.deck.audio.state().status==='ready');check('sound loading can be retried after an asset failure',await missing.evaluate(()=>window.deck.audio.state().enabled));await missing.close();
check('no browser runtime errors',errors.length===0,{errors});await browser.close();
const encode=spawnSync('ffmpeg',['-hide_banner','-loglevel','error','-y','-i','qa/place-journey-preview.mp4',...clips.map(c=>['-i',`qa/audio/${c.name}.wav`]).flat(),'-filter_complex',`[1:a][2:a][3:a][4:a][5:a][6:a]concat=n=6:v=0:a=1[a]`,'-map','0:v','-map','[a]','-c:v','copy','-c:a','aac','-b:a','192k','-t','24','-movflags','+faststart','qa/sound-journey-preview.mp4'],{stdio:'inherit'});
check('24s camera preview receives the exact same rendered mix',encode.status===0);
await fs.writeFile('qa/audio-checks.json',JSON.stringify({date:'2026-10-06',results,renders,errors,passed:results.filter(r=>r.pass).length,total:results.length},null,2));if(results.some(r=>!r.pass))process.exitCode=1;
