import fs from 'node:fs/promises';
import crypto from 'node:crypto';
import {chapters,allCues,evidence,formatTime} from '../src/content.ts';
import {placeFor} from '../src/Places.ts';
await fs.mkdir('docs',{recursive:true});
const sourceNames=['cinematic_3d_slides_motion_spec.md','ted_talk_master_outline.md','ted_talk_full_script.md'];
const files=[];for(const name of sourceNames){const buffer=await fs.readFile(`sources/${name}`);files.push({name,sha256:crypto.createHash('sha256').update(buffer).digest('hex')});}
await fs.writeFile('sources/manifest.json',JSON.stringify({originalDirectory:'C:/Users/BKungBK/.gemini/antigravity/scratch/human_vs_ai_seminar',files,backup:'D:/Project/AI_VS_HUMAN_before_rebuild_20261005_183618.zip',archivedDirectory:'D:/Project/AI_VS_HUMAN_archived_20261005_183618',cleanup:'Old project moved out after ZIP verified. Empty workspace verified before fresh scaffold.'},null,2));
let script='# บทสำหรับผู้พูด — ฉบับข้อมูลตรงกับสไลด์ใหม่\n\nกรอบเวลา 50 นาที เป็น presenter cues และคำอธิบายสำหรับซ้อมร่วมกับต้นฉบับ ไม่ใช่เสียงบรรยายที่จับเวลาอัตโนมัติ ช่วงเกมดำเนินจากระบบภายนอก ผู้พูดขยายตัวอย่างหรืออภิปรายในช่วง hold ได้ ห้ามใช้ผลผู้ชนะสมมติจากต้นฉบับ\n\n';
let sheet='# ตารางคิว — 16 บท / 43 คิว\n\nArrowRight / Space เดินหน้า · ArrowLeft ย้อน · P หยุดภาพ · F เต็มจอ · B fade ดับจอ · H ซ่อน controls · C เลือกบท · N เปิด presenter แยกหน้าต่าง\n\n| คิว | เวลาเริ่มบท | ผู้พูด | จอ | ข้อความหลัก |\n|---|---|---|---|---|\n';
let story='# Storyboard — Modern Dark Neo-Pastel\n\nกล้องใช้ expo.inOut / power4.inOut, card reveals power3.out / back.out(1.2). Punch-in 0.6s + glide 1.05s. Push-through 1.75s หลัง handoff. Dolly: Z 2520→1500 และชดเชย FOV เพื่อคงสเกลระนาบหลัก. กล้องเดียวขับ HTML text, cards, background 3 ระยะ และ particles; ข้อความเข้าแบบ Z/rotateX/rotateY เป็นบรรทัดสมบูรณ์แล้วกลับ identity. ข้อความเก่าเลื่อน Z และ fade 0.44s ก่อนหัวข้อใหม่เริ่ม 0.57s. Header/footer อยู่ screen space. กล้องและข้อความอ่านตรงภายใน 2.4s; ย้อนคิวกลับทิศการเคลื่อน. ดู docs/spatial-motion-direction.md. Live hold ไม่ทำให้คิวถัดไปปรากฏ เสียง: ไม่มีทุกคิว.\n\n';
for(const c of chapters){script+=`## ${c.id} · ${c.title} · ${formatTime(c.start)}–${formatTime(c.end)}\n\n`;story+=`## ${c.id} · ${c.title}\n\n`;for(const cue of c.cues){const title=cue.title.replaceAll('\n',' / ');script+=`### ${cue.id} · ${title}\n\n**${cue.speaker}** — ${cue.notes}\n\n`;sheet+=`| ${cue.id} | ${formatTime(c.start)} | ${cue.speaker} | ${cue.kind} | ${title} |\n`;story+=`### ${cue.id} · ${title}\n\n- On screen: ${title}. ${cue.subtitle}\n- Visual: ${cue.visual||'centered text on slate'}; layers: ${cue.kind==='placeholder'?'slate + foreground text':'three far CSS3D planes + atmosphere/particles + spatial SVG/photo glass cards + native HTML typography in the same perspective camera'}\n- Camera/entry: ${cue.motion}; ${cue.kind==='placeholder'?'fade 0.35s then hold':'card reveal from 0.53s; native text lines from 0.57s with 0.105s stagger; camera pulls wide then travels inward and lands by 2.4s (initial load starts earlier)'}\n- Hold: ${cue.kind==='placeholder'?'static':'contextual ambient phase repeats every '+cue.loop+'s; no facts revealed by the loop'}\n- Exit: ${cue.kind==='placeholder'?'0.22s fade':'old card group moves in Z with Y/X rotation, fades 0.46s; old text lines move forward/tilt and fade 0.44s; next cue camera begins from captured actual pose'}\n- Evidence: ${cue.facts.map(f=>evidence[f].label).join('; ')||'Presenter viewpoint / illustrative composition'}\n\n`;}}
story=story.replaceAll('background 3 ระยะ','ฉาก SVG 4 ระยะ').replaceAll('three far CSS3D planes','four authored scenic CSS3D planes').replaceAll('0.57s','1.25s').replaceAll('0.53s','1.15s').replaceAll('2.4s','2.8s').replaceAll('docs/spatial-motion-direction.md','docs/place-journey-direction.md');
const places=[];
for(const {cue} of allCues){
 const place=placeFor(cue);places.push({cue:cue.id,kind:cue.kind,...place});
 if(cue.kind==='content')story=story.replace(`### ${cue.id} · ${cue.title.replaceAll('\n',' / ')}`,`### ${cue.id} · ${cue.title.replaceAll('\n',' / ')}\n\n- Place: ${place.label}; station ${JSON.stringify(place.anchor)}; incoming route ${place.route}. Camera leaves the previous actual pose, follows a curved world path from 0.16–1.71s, passes three scenic thresholds, then lands beside the native text.`);
}
await fs.writeFile('docs/place-map.json',JSON.stringify(places,null,2));
await fs.writeFile('docs/presenter-script.md',script);await fs.writeFile('docs/cue-sheet.md',sheet);await fs.writeFile('docs/storyboard.md',story);
await fs.writeFile('sources/evidence.json',JSON.stringify(Object.values(evidence),null,2));
let facts='# ข้อมูลและข้อแก้ไขจากต้นฉบับ\n\nเอกสารต้นฉบับเก็บไว้โดยไม่แก้ ข้อความบนจอและ presenter ใช้ข้อมูลร่วมกันจาก src/content.ts ตารางนี้บันทึกขอบเขตหลักฐานและข้อจำกัดของการเข้าถึง ไม่อ้างว่าทุกหน้าเปิดอ่านต้นฉบับได้สำเร็จ\n\n';for(const e of Object.values(evidence))facts+=`## ${e.label}\n\n[แหล่งอ้างอิง](${e.url})\n\n${e.finding}\n\nสถานะ: ${e.status}\n\n`;
facts+='## ข้ออ้างที่ตัดออกหรือเปลี่ยน\n\n- AlphaFold3 ได้โนเบลโดยตรง → ระบุผลงานและ AlphaFold2 ตามเอกสารรางวัล\n- Jagged Frontier +40% เร็วขึ้น / -19% คุณภาพพัง → ใช้ working-paper 2023 ที่ระบุคุณภาพ >40%, ความเร็ว >25%, งานเสร็จ >12%; ไม่ปะปนเวอร์ชันหรือตัวชี้วัด\n- คนไข้โหวตบอต 80% → ผู้เชี่ยวชาญสุขภาพเลือกคำตอบ 78.6%\n- Tessa ปี 2024/ทำให้คนตาย → ระงับในปี 2023 หลังรายงานคำแนะนำเสี่ยง ไม่อ้างผู้เสียชีวิต\n- CrowdStrike เกิดจาก generative AI เขียนโค้ด → เหตุ update ระบบ ใช้บทเรียนการทดสอบ\n- คน+AI แย่กว่าคนเสมอ → แยก best baseline กับ human-only\n- EU AI Act บังคับคนอนุมัติทุกระบบ → Article 14 สำหรับ high-risk systems\n- คดี Google/เยอรมนี, Kask และ Brookins ที่ตรวจยืนยันไม่ครบ → ไม่ใช้บนจอหรือบทใหม่\n- เห็ดมั่นใจ 99.8% / สัดส่วนคันเร่งสากล → สถานการณ์จำลอง ไม่ใช่ค่าที่พิสูจน์\n- ผลผู้ชนะจากต้นฉบับ → ไม่กำหนดล่วงหน้า\n\n## สิทธิ์ภาพ\n\nThe Starry Night: public domain / PD-Art. Death Cap: Archenzo, CC BY-SA 3.0 (resize only). FLAMINGONE: © Miles Astray, ใช้ภาพ preview จากผู้สร้างเป็นข้อมูลอ้างอิงสำหรับอภิปรายในงานท้องถิ่น; ไม่อ้าง open license หรือสิทธิ์แจกจ่ายต่อ ต้องจัดการ license ก่อนเผยแพร่หรือใช้เชิงพาณิชย์ ดู sources/asset-provenance.json.\n';
await fs.writeFile('docs/facts-and-rights.md',facts);
console.log(`Delivery docs: ${chapters.length} chapters / ${allCues.length} cues`);
