import {chromium} from 'playwright';
import {spawnSync} from 'node:child_process';
import fs from 'node:fs/promises';
import {chapters} from '../src/content.ts';
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--use-angle=d3d11']});
const context=await browser.newContext({viewport:{width:1920,height:1080},deviceScaleFactor:1}),page=await context.newPage(),checks=[],errors=[];
page.on('pageerror',e=>errors.push(e.message));
const test=(name,pass,detail)=>{checks.push({name,pass:!!pass,detail});console.log(pass?'PASS':'FAIL',name);};
const settle=()=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
const go=async(s,b)=>{await page.evaluate(([s,b])=>window.deck.go(s,b),[s,b]);await settle();};
await page.goto('http://127.0.0.1:5173/?clean=1');await page.waitForFunction(()=>window.deck?.ready);await page.evaluate(()=>window.deck.pause());
await go(8,0);await page.evaluate(()=>window.deck.seek(4));await go(8,1);await page.evaluate(()=>window.deck.seek(.52));
test('outgoing text gone before new headline',await page.locator('.outgoing-copy').evaluate(e=>Number(getComputedStyle(e).opacity)===0));
test('header not duplicated during handoff',await page.locator('.stage-header').count()===1);
await page.screenshot({path:'qa/handoff-final.png'});
await page.keyboard.press('f');await page.waitForFunction(()=>!!document.fullscreenElement);test('fullscreen opens from keyboard',await page.evaluate(()=>!!document.fullscreenElement));await page.keyboard.press('f');await page.waitForFunction(()=>!document.fullscreenElement);test('fullscreen exits from keyboard',await page.evaluate(()=>!document.fullscreenElement));
await page.evaluate(()=>window.deck.seek(4));
const presenter=await context.newPage();await presenter.goto('http://127.0.0.1:5173/?presenter=1');await presenter.waitForSelector('.notes');
await presenter.waitForFunction(()=>window.deck?.state().cue==='09.02');await presenter.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
test('full revised dialogue in presenter',await presenter.locator('.notes').textContent().then(t=>t.includes('585')&&t.includes('78.6%')));
test('stage directions separate from dialogue',await presenter.locator('.stage-direction').count()===1&&await presenter.locator('.fact-guard').count()===1);
await presenter.screenshot({path:'qa/presenter.png'});
await presenter.locator('.presenter-navigation button').nth(1).click();await settle();test('updated presenter still controls projection',await page.evaluate(()=>window.deck.state().cue==='09.03'));await presenter.close();
await go(12,1);await page.evaluate(()=>window.deck.seek(8));
const measure=()=>page.evaluate(()=>[...document.querySelectorAll('.spatial-host [data-flow]')].map(el=>({opacity:Number(el.style.opacity),transform:el.style.transform})));
await page.evaluate(()=>window.deck.seek(4));const start=await measure();await page.evaluate(t=>window.deck.seek(t),4+chapters[12].cues[1].loop);const end=await measure();
test('verification flow returns to same phase',JSON.stringify(start)===JSON.stringify(end),{start,end});
const loopCases=[[2,1],[5,3],[6,1],[9,0],[14,0]].map(([s,b])=>[s,b,chapters[s].cues[b].loop]);
const ambientSnapshot=()=>page.evaluate(()=>[...document.querySelectorAll('.spatial-host *')].map(el=>({style:el.getAttribute('style'),confidence:el.hasAttribute('data-confidence')?el.textContent:null})));
for(const [s,b,loop] of loopCases){
 await go(s,b);await page.evaluate(()=>window.deck.seek(20));await settle();const a=await ambientSnapshot();const pa=`qa/join-${s+1}-${b+1}-a.png`;await page.screenshot({path:pa});
 await page.evaluate(t=>window.deck.seek(20+t),loop);await settle();const z=await ambientSnapshot();const pz=`qa/join-${s+1}-${b+1}-b.png`;await page.screenshot({path:pz});
 const compare=spawnSync('python',['-c',"from PIL import Image,ImageChops; import json,sys; d=ImageChops.difference(Image.open(sys.argv[1]).convert('RGB'),Image.open(sys.argv[2]).convert('RGB')); p=list(d.get_flattened_data()); print(json.dumps({'maximumChannelDelta':max(max(v) for v in p),'changedPixels':sum(v!=(0,0,0) for v in p)}))",pa,pz],{encoding:'utf-8'});
 if(compare.status!==0)throw new Error(compare.stderr);const raster=JSON.parse(compare.stdout);
 test(`ambient join ${s+1}.${b+1}`,JSON.stringify(a)===JSON.stringify(z)&&raster.maximumChannelDelta<=1&&raster.changedPixels<=2073,{raster,note:'Identical DOM/phase; GPU raster allowance ≤1 RGB level in ≤0.1% pixels.'});
}
await go(0,0);await page.evaluate(()=>window.deck.seek(4));await page.screenshot({path:'qa/prototypes/opening.png'});
await page.evaluate(()=>window.deck.resume());
const intervals=await page.evaluate(()=>new Promise(resolve=>{const arr=[];let last=0;function tick(now){if(last)arr.push(now-last);last=now;if(arr.length<120)requestAnimationFrame(tick);else resolve(arr);}requestAnimationFrame(tick);}));
const sorted=intervals.slice().sort((a,b)=>a-b),p50=sorted[59],p95=sorted[113];
await fs.writeFile('qa/performance.json',JSON.stringify({viewport:[1920,1080],samples:120,rafIntervalMs:{p50,p95},approxMedianFPS:1000/p50,note:'Headless Chrome on this machine, GPU ANGLE D3D11. No real-projector performance claim.'},null,2));
test('no runtime errors after final refinement',errors.length===0,errors);
const noGL=await context.newPage();await noGL.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){if(type==='webgl'||type==='webgl2'||type==='experimental-webgl')return null;return original.call(this,type,...args);};});await noGL.goto('http://127.0.0.1:5173/?clean=1&scene=5&cue=3');await noGL.waitForFunction(()=>window.deck?.ready);await noGL.evaluate(()=>{window.deck.pause();window.deck.seek(4);});test('no WebGL at startup retains full content',await noGL.evaluate(()=>window.deck.state().fallback&&document.querySelectorAll('.spatial-host [data-card]').length===3));await noGL.screenshot({path:'qa/fallback-startup.png'});await noGL.close();
await fs.writeFile('qa/final-checks.json',JSON.stringify({checks,errors,pass:checks.every(c=>c.pass)},null,2));
await browser.close();if(checks.some(c=>!c.pass))process.exitCode=1;
