import {chromium} from 'playwright';
import fs from 'node:fs/promises';
import {spawnSync} from 'node:child_process';
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--use-angle=d3d11']});
const page=await browser.newPage({viewport:{width:1920,height:1080},deviceScaleFactor:1}),checks=[],errors=[];
page.on('pageerror',e=>errors.push(e.message));
const check=(name,pass,detail)=>{checks.push({name,pass:!!pass,detail});console.log(pass?'PASS':'FAIL',name);};
const settle=()=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
const go=async(s,b)=>{await page.evaluate(([s,b])=>window.deck.go(s,b),[s,b]);await settle();};
const seek=async t=>{await page.evaluate(t=>window.deck.seek(t),t);await settle();};
const state=()=>page.evaluate(()=>window.deck.state());
const line=()=>page.locator('.spatial-host [data-text-line]').first().evaluate(e=>{const m=new DOMMatrixReadOnly(getComputedStyle(e).transform);return {opacity:Number(getComputedStyle(e).opacity),z:m.m43,yaw:m.m13,pitch:m.m23,identity:m.isIdentity};});
await page.goto('http://127.0.0.1:5173/?clean=1');await page.waitForFunction(()=>window.deck?.ready);await page.evaluate(()=>window.deck.pause());
await go(8,0);await seek(4);await go(8,1);await seek(.2);
const oldLine=await page.locator('.outgoing-copy [data-text-line]').first().evaluate(e=>new DOMMatrixReadOnly(getComputedStyle(e).transform).m43);
check('departure moves native text through Z',oldLine>10,{z:oldLine});
await seek(.52);check('old headline clears before incoming title',await page.locator('.outgoing-copy').evaluate(e=>Number(getComputedStyle(e).opacity)===0));
await seek(.75);const enterLine=await line();check('incoming title has depth and two-axis tilt',enterLine.z<0&&Math.abs(enterLine.yaw)>.005&&Math.abs(enterLine.pitch)>.005&&enterLine.opacity>0&&enterLine.opacity<1,enterLine);
await seek(2.4);const hold=await line(),holdState=await state();check('read plane settles sharp and frontal',hold.identity&&hold.opacity===1&&holdState.cameraZ===1500&&holdState.cameraYaw===0&&holdState.cameraPitch===0,{hold,holdState});
check('three distinct far background planes',await page.evaluate(()=>{const planes=[...document.querySelectorAll('.spatial-host .depth-plane')];return planes.length===3&&new Set(planes.map(e=>e.style.transform)).size===3;}));
const clips=[{name:'arc',from:[0,0],to:[0,2]},{name:'punch',from:[8,0],to:[8,1]},{name:'push',from:[8,2],to:[9,0]},{name:'dolly',from:[5,2],to:[5,3]},{name:'reverse',from:[0,3],to:[0,2]}];
for(const clip of clips){
 await go(...clip.from);await seek(4);await go(...clip.to);await seek(.55);const start=await state();await seek(2.4);const end=await state();
 check(`${clip.name} camera translates and rotates`,Math.abs(start.cameraZ-end.cameraZ)>300&&Math.abs(start.cameraYaw)>.5,{start,end});
 if(clip.name==='dolly')check('dolly counter-zooms projection',Math.abs(start.fov-end.fov)>10,{start:start.fov,end:end.fov});
 if(clip.name==='reverse')check('backward navigation reverses camera arc',start.cameraX<0&&start.cameraYaw>0,start);
}
await go(5,2);await seek(4);await go(5,3);const dollyBounds=[];
for(const t of [.8,1.05,1.4,1.8,2.4]){await seek(t);dollyBounds.push({time:t,bounds:await page.locator('.spatial-host [data-text-line]').evaluateAll(lines=>lines.map(el=>{const r=el.getBoundingClientRect();return {left:r.left,right:r.right};}))});}
check('incoming Thai lines stay inside frame during dolly',dollyBounds.every(f=>f.bounds.every(r=>r.left>=64&&r.right<=1842)),dollyBounds);
await go(8,1);await seek(4);await go(5,3);await seek(0);const light0=await page.locator('.spatial-host .depth-plane').first().evaluate(e=>e.style.getPropertyValue('--depth-rgb'));
await seek(.5);const lightMiddle=await page.locator('.spatial-host .depth-plane').first().evaluate(e=>e.style.getPropertyValue('--depth-rgb'));
await seek(1.2);const light1=await page.locator('.spatial-host .depth-plane').first().evaluate(e=>e.style.getPropertyValue('--depth-rgb'));
check('ambient light blends through a middle color',lightMiddle!==light0&&lightMiddle!==light1,{light0,lightMiddle,light1});
const snapshot=()=>page.evaluate(()=>({state:window.deck.state(),styles:[...document.querySelectorAll('.spatial-host *, .outgoing *')].map(e=>e.getAttribute('style'))}));
await go(0,0);await seek(4);await go(0,2);await seek(.85);const a=await snapshot();await page.screenshot({path:'qa/spatial-motion/seek-a.png'});
await seek(4);await seek(.85);const b=await snapshot();await page.screenshot({path:'qa/spatial-motion/seek-b.png'});
const diff=spawnSync('python',['-c',"from PIL import Image,ImageChops; import json; a=Image.open('qa/spatial-motion/seek-a.png').convert('RGB'); b=Image.open('qa/spatial-motion/seek-b.png').convert('RGB'); d=ImageChops.difference(a,b); pixels=list(d.get_flattened_data()); print(json.dumps({'maximumChannelDelta':max(max(p) for p in pixels),'changedPixels':sum(p!=(0,0,0) for p in pixels)}))"],{encoding:'utf-8'});
if(diff.status!==0)throw new Error(diff.stderr);const raster=JSON.parse(diff.stdout);
check('seek reconstructs whole transition in either direction',JSON.stringify(a)===JSON.stringify(b)&&raster.maximumChannelDelta<=1&&raster.changedPixels<=2073,{raster,note:'Identical camera/DOM; allowance for GPU compositing rounding is ≤1 RGB level in ≤0.1% pixels.'});
const before=await state();await go(5,3);await seek(0);const after=await state();check('interrupted transition preserves captured camera pose',Math.abs(before.cameraZ-after.cameraZ)<.01&&Math.abs(before.cameraYaw-after.cameraYaw)<.01,{before,after});
for(const t of [.08,.2,.39,.56,.85]){await seek(t);await go(8,1);await seek(t);await go(5,3);}await seek(4);
check('rapid changes keep exactly one live text and world',await page.evaluate(()=>document.querySelectorAll('.spatial-host .text-stage').length===1&&document.querySelectorAll('.spatial-host .visual-world').length===1&&document.querySelectorAll('.outgoing-copy').length<=1));
await go(1,0);await seek(.7);const placeholder=await state(),pLine=await line();check('game remains centered static text',placeholder.backgroundLayers===0&&placeholder.particles===0&&pLine.identity&&pLine.opacity===1,placeholder);
await go(0,2);await page.emulateMedia({reducedMotion:'reduce'});await seek(.75);const full=await line();check('system motion preference retains spatial text entry',!full.identity&&await page.evaluate(()=>window.deck.state().journey.active),full);
await page.emulateMedia({reducedMotion:'no-preference'});await seek(4);await page.evaluate(()=>window.deck.setFallback());await settle();await seek(.75);check('native spatial text survives WebGL fallback',await page.evaluate(()=>window.deck.state().fallback&&document.querySelector('.spatial-host [data-text-line]').getBoundingClientRect().width>0));
check('one timeline drives camera, cards and text',await page.evaluate(()=>window.__timelines.cards===window.__timelines.copy));
check('no runtime errors',errors.length===0,errors);
await fs.writeFile('qa/spatial-checks.json',JSON.stringify({checks,errors,pass:checks.every(c=>c.pass)},null,2));
await browser.close();if(checks.some(c=>!c.pass))process.exitCode=1;
