export type Visual = 'opening'|'biology'|'question'|'art'|'poetry'|'flamingo'|'attribution'|'individual'|'diversity'|'tensor'|'protein'|'strategy'|'frontier'|'frontier-data'|'mushroom'|'chat'|'empathy'|'tokens'|'tessa'|'gate'|'case'|'liability'|'synergy'|'design'|'outage'|'oversight'|'formula'|'different'|'future'|'responsibility'|'thanks';
import {loopDuration} from './MotionTiming.ts';
export type Speaker = 'Human'|'AI'|'Both';
export interface Evidence {id:string;label:string;url:string;finding:string;status:string}
export interface Cue {id:string;kind:'content'|'placeholder';title:string;subtitle:string;eyebrow:string;speaker:Speaker;visual?:Visual;facts:string[];notes:string;motion:'push'|'punch'|'dolly'|'arc'|'fade';loop:number}
export interface Chapter {id:string;title:string;start:number;end:number;cues:Cue[]}
export const evidence:Record<string,Evidence>={
 korteling:{id:'korteling',label:'Korteling et al. · 2021',url:'https://www.frontiersin.org/journals/artificial-intelligence/articles/10.3389/frai.2021.622364/full',finding:'Human and artificial intelligence have different capabilities and constraints; conceptual review, not a universal speed benchmark.',status:'Primary article'},
 poetry:{id:'poetry',label:'Porter & Machery · 2024',url:'https://www.nature.com/articles/s41598-024-76900-1.pdf',finding:'Non-expert readers identified poem origin with 46.6% accuracy in these experiments. AI poems were rated favorably on selected attributes.',status:'Primary paper'},
 attribution:{id:'attribution',label:'Grassini & Koivisto · 2024',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC10876601/',finding:'Perceived authorship affected preferences for artworks, regardless of the actual source. The flamingo story is a separate case, not part of this experiment.',status:'Primary paper; abstract cross-checked'},
 flamingo:{id:'flamingo',label:'Miles Astray · FLAMINGONE',url:'https://www.milesastray.com/iconic-imagery',finding:'The photographer describes winning jury and audience awards in an AI category with a real flamingo photograph; image taken in Aruba in 2022, award story in 2024.',status:'Creator account'},
 diversity:{id:'diversity',label:'Doshi & Hauser · 2024',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC11244532/',finding:'In a short-story experiment, AI ideas improved individual creativity ratings, particularly for less creative writers, while making stories more similar.',status:'Primary paper'},
 tensor:{id:'tensor',label:'Fawzi et al. · Nature 2022',url:'https://www.nature.com/articles/s41586-022-05172-4',finding:'AlphaTensor discovered provably correct and efficient matrix multiplication algorithms for studied matrix sizes and hardware objectives.',status:'Primary paper'},
 nobel:{id:'nobel',label:'Nobel Chemistry · 2024',url:'https://www.nobelprize.org/uploads/2024/10/advanced-chemistryprize2024.pdf',finding:'Baker: computational protein design. Hassabis and Jumper: protein structure prediction; AlphaFold2 is discussed in the award background.',status:'Official scientific background'},
 frontier:{id:'frontier',label:'Dell’Acqua et al. · 2023 working paper',url:'https://aiinstitute.hbs.edu/navigating-the-jagged-technological-frontier/',finding:'2023 working-paper version: 758 consultants; within frontier, >40% higher human-rated quality, >25% faster, >12% more tasks. No claim of 40% speed gain. Outside-frontier task can worsen outcomes.',status:'Research institute summary of working paper; deliberately versioned'},
 ayers:{id:'ayers',label:'Ayers et al. · JAMA 2023',url:'https://jamanetwork.com/journals/jamainternalmedicine/fullarticle/2804309',finding:'Licensed health-care professionals preferred chatbot answers in 78.6% of 585 evaluations of answers to 195 questions. Not patient votes or clinical outcomes.',status:'Primary paper'},
 tessa:{id:'tessa',label:'Tessa · NEDA · 2023',url:'https://www.wired.com/story/tessa-chatbot-suspended/',finding:'NEDA paused Tessa in May 2023 after reports of weight-loss advice; reporting includes direct comments from NEDA CEO. No verified death claimed.',status:'Contemporaneous reporting and direct NEDA comments; primary statement unavailable'},
 court:{id:'court',label:'Moffatt v. Air Canada · 2024 BCCRT 149',url:'https://www.canlii.org/en/bc/bccrt/doc/2024/2024bccrt149/2024bccrt149.html',finding:'The tribunal held Air Canada responsible for negligent misrepresentation in chatbot bereavement-fare information. A civil compensation matter, not a criminal conviction or universal liability rule.',status:'Decision identified; direct host blocked, contemporaneous accounts cross-checked'},
 synergy:{id:'synergy',label:'Vaccaro et al. · Nature 2024',url:'https://www.nature.com/articles/s41562-024-02024-1',finding:'106 experiments / 370 effect sizes. Combined systems were worse than the best human or AI baseline on average, but better than human-only on average; results varied by task.',status:'Primary meta-analysis'},
 crowdstrike:{id:'crowdstrike',label:'CrowdStrike · RCA · Aug 2024',url:'https://www.crowdstrike.com/en-us/blog/channel-file-291-rca-available/',finding:'A July 19, 2024 content configuration update caused widespread Windows sensor outage. Used as a deployment/testing lesson, not evidence that generative AI wrote the update.',status:'Company root-cause analysis'},
 oversight:{id:'oversight',label:'EU AI Act · Article 14',url:'https://eur-lex.europa.eu/eli/reg/2024/1689/oj/eng',finding:'Article 14 addresses human oversight of high-risk AI. Duties depend on risk category, actor and applicable provisions. No blanket human-in-the-loop rule for all AI.',status:'Official legislation'},
 mushroom:{id:'mushroom',label:'Archenzo · CC BY-SA 3.0',url:'https://commons.wikimedia.org/wiki/File:Amanita_phalloides_1.JPG',finding:'Photo of Amanita phalloides. Confidence gauge is invented for the activity and is not a medical or identification result.',status:'Image provenance; fictional confidence values'}
};
const make=(id:string,title:string,subtitle:string,visual:Visual,speaker:Speaker,eyebrow:string,notes:string,facts:string[]=[],motion:Cue['motion']='push'):Cue=>({id,kind:'content',title,subtitle,visual,speaker,eyebrow,notes,facts,motion,loop:loopDuration(visual)});
const hold=(id:string,title:string,subtitle:string,notes:string):Cue=>({id,kind:'placeholder',title,subtitle,eyebrow:'',speaker:'Both',notes,facts:[],motion:'fade',loop:0});
export const chapters:Chapter[]=[
 {id:'01',title:'THE CLASH',start:0,end:180,cues:[
  make('01.01','HUMAN\nvs AI','The Sparring Minds','opening','Both','DIFFERENT MINDS. ONE QUESTION.','Human: สวัสดีอาจารย์และเพื่อน ๆ ครับ วันนี้เราไม่ได้ถามเพียงว่าใครเก่งกว่า แต่จะลองมองให้ชัดว่าสติปัญญาสองแบบเหมาะกับหน้าที่อะไร และเมื่อเกิดผลกระทบ ใครต้องรับผิดชอบ เราจะเดินผ่านความคิดสร้างสรรค์ ตรรกะ ความเห็นอกเห็นใจ และการร่วมมือในเวลา 50 นาที'),
  hold('01.02','สแกนเพื่อเข้าร่วม','กรอกชื่อ เลือกกลุ่ม แล้วรอเกมเริ่ม','ผู้เข้าร่วมสแกน QR บนจอ กรอกชื่อเล่นและเลือกกลุ่มเพียงครั้งเดียว จากนั้นมือถือจะรอและเปลี่ยนเป็นหน้าเกมโดยอัตโนมัติเมื่อสไลด์ถึงคิวเกม ผู้จัดเป็นผู้กดเริ่ม'),
  make('01.03','คิดต่าง\nเพราะสร้างมาต่างกัน','ชีววิทยา · ประสบการณ์ · การคำนวณ','biology','AI','TWO KINDS OF INTELLIGENCE','AI: มนุษย์มีข้อจำกัดเรื่องความจำ ความเหนื่อยล้า และการคำนวณ ส่วน AI ใช้รูปแบบจากข้อมูลทำงานได้รวดเร็วในหลายบริบท Korteling และคณะอภิปรายความต่างนี้ แต่ไม่ได้พิสูจน์ว่า AI เหนือมนุษย์ในทุกเรื่อง เราจึงควรเปรียบเทียบงานและเงื่อนไข ไม่ใช่เหมารวมสติปัญญาทั้งหมด',['korteling'],'arc'),
  make('01.04','ใครควรทำอะไร?','และใครยังคงต้องรับผิดชอบ?','question','Human','THE QUESTION THAT MATTERS','Human: ถ้าเครื่องมือเสนอทางเลือกได้เร็ว แต่ข้อเสนอนั้นกระทบคนจริง ผู้ใช้และองค์กรยังต้องตัดสินใจตามหน้าที่ของตน คำถามของเราคือจะแบ่งงานและออกแบบการตรวจสอบอย่างไร ไปเริ่มจากความไว้ใจกันก่อน',[],'punch')
 ]},
 {id:'02',title:'TRUST',start:180,end:360,cues:[hold('02.01','THE TRUST\nTUG-OF-WAR','GAME 01 · ชักเย่อสติปัญญา','ผู้เล่นเลือกฝั่ง Human หรือ AI แล้วแตะพร้อมกัน 10 วินาที จอฉายแสดงแรงเฉลี่ยและคะแนนกลุ่มจากข้อมูลจริง ผู้จัดกดเริ่มและยืนยันผลก่อนสไลด์ไปต่อ')]},
 {id:'03',title:'CREATIVITY',start:360,end:720,cues:[
  make('03.01','ศิลปะมีชีวิต\nอยู่เบื้องหลัง','Lived experience','art','Human','THE SOUL OF CREATIVITY','Human: เมื่อเรามอง The Starry Night เราอาจมองเห็นทั้งสี ฝีแปรง และชีวิตของ Van Gogh ความหมายของงานไม่ได้มาจากคะแนนประเมินอย่างเดียว ประสบการณ์ของผู้สร้างและผู้ชมเป็นอีกมิติหนึ่ง นี่เป็นมุมมองทางสุนทรียศาสตร์ของผู้พูด ไม่ใช่ผลทดลองพิสูจน์คุณค่าศิลปะ'),
  make('03.02','ถ้าปิดชื่อผู้สร้าง\nคุณแยกออกไหม?','บทกวีที่อ่านได้ ไม่ได้บอกที่มาเสมอไป','poetry','AI','STATISTICAL TOKENS','AI: Porter และ Machery ทดลองกับผู้อ่านบทกวีทั่วไป ผู้เข้าร่วมจำแนกแหล่งกำเนิดได้ถูก 46.6% และให้คะแนนบทกวี AI สูงกว่าในคุณลักษณะบางด้าน ผลนี้บอกข้อจำกัดของการจำแนกในงานทดลอง ไม่ได้พิสูจน์ว่ากวีมนุษย์หมดคุณค่า',['poetry'],'punch'),
  hold('03.05','SWIPE\nCOURT','GAME 02 · ปัดซ้ายคน / ปัดขวา AI',"Swipe Court: ผู้เล่นปัดเลือกที่มาของภาพ 8 รอบ ทุกเครื่องเริ่มและเฉลยพร้อมกัน จอฉายแสดงภาพ สถิติห้อง และคะแนนกลุ่มจากข้อมูลจริง ผู้จัดกดเริ่มและยืนยันผลจากหน้าควบคุม"),
  make('03.03','FLAMINGONE','ภาพจริง ในหมวดประกวด AI','flamingo','Human','A REAL PHOTOGRAPH. AN UNEXPECTED LABEL.','Human: ภาพของ Miles Astray ถ่ายนกฟลามิงโกที่กำลังไซ้ขนใน Aruba ปี 2022 เรื่องการประกวดเป็นข่าวในปี 2024 ผู้สร้างบอกว่าภาพจริงได้ทั้งรางวัลจากกรรมการและผู้ชมในหมวด AI กรณีนี้ชวนให้เราคิดว่าเราใช้ภาพหรือใช้ป้ายกำกับตัดสินงาน',['flamingo'],'punch'),
  make('03.04','ผลงานเดิม\nป้ายใหม่','ความเชื่อว่าใครสร้าง มีผลต่อการประเมิน','attribution','Human','ATTRIBUTION BIAS','Human: งานของ Grassini และ Koivisto ศึกษาความชอบต่องานศิลป์และการรับรู้แหล่งกำเนิด เมื่อคนเชื่อว่างานมาจาก AI การประเมินอาจเปลี่ยน แม้แหล่งกำเนิดจริงจะเป็นอีกแบบ ภาพในคิวนี้สาธิตแนวคิด ไม่มีคะแนนประเมินที่แต่งขึ้น และกรณี FLAMINGONE เป็นเรื่องแยกจากการทดลอง',['attribution'],'arc')
 ]},
 {id:'04',title:'IDEAS',start:720,end:955,cues:[
  hold('04.01','CAPTION &\nPROMPT BATTLE','GAME 03 · ดวลแคปชั่น','ผู้เล่นเขียนแคปชั่น ส่งตรวจ และโหวตเลือกตัวแทนกับผลงานกลุ่มอื่นผ่านมือถือ จอฉายแสดงผลงานและคะแนนสด ผู้จัดตรวจงานแล้วกดเริ่มแต่ละช่วงและยืนยันผล'),
  make('04.02','เก่งขึ้นรายคน','AI ช่วยเสนอไอเดีย ในการทดลองเรื่องสั้น','individual','AI','INDIVIDUAL ENHANCEMENT','AI: Doshi และ Hauser ให้ผู้เข้าร่วมเขียนเรื่องสั้นโดยมีหรือไม่มีไอเดียจาก AI กลุ่มที่ได้รับไอเดียสามารถได้คะแนนความสร้างสรรค์ดีขึ้น โดยเฉพาะผู้เขียนที่เดิมมีคะแนนต่ำกว่า เราต้องระบุบริบทว่าเป็นเรื่องสั้นและการประเมินในงานทดลอง ไม่ใช่ผลสากลกับทุกอาชีพ',['diversity'],'punch'),
  make('04.03','แต่ไอเดีย\nคล้ายกันมากขึ้น','คุณภาพ กับ ความหลากหลาย เป็นคนละคำถาม','diversity','Human','COLLECTIVE DIVERSITY','Human: ในงานทดลองเดียวกัน เรื่องที่ใช้ AI ช่วยมีความคล้ายกันมากขึ้น นี่เป็นข้อแลกเปลี่ยนที่เราควรมองเห็น ไม่ได้แปลว่าสังคมทั้งโลกสูญเสียความคิดสร้างสรรค์ทันที ลองใช้ AI สร้างทางเลือก แล้วตั้งใจค้นหามุมที่ต่างและเหมาะกับเรา',['diversity'],'arc')
 ]},
 {id:'05',title:'ACT 1 RESULTS',start:955,end:960,cues:[hold('05.01','FLASH LEADERBOARD','ACT 01 · สรุปอันดับ','ช่วงคะแนน 5 วินาทีตามคิวบท ผู้ควบคุมกดเปลี่ยนเอง ไม่มีคะแนนหรืออันดับสมมติ')]},
 {id:'06',title:'THE FRONTIER',start:960,end:1320,cues:[
  make('06.01','เมื่อ AI\nค้นพบทางลัด','AlphaTensor · Matrix multiplication','tensor','AI','THE POWER OF FORMAL REASONING','AI: AlphaTensor ค้นหาอัลกอริทึมคูณเมทริกซ์ที่มีประสิทธิภาพขึ้นในกรณีที่ศึกษา ผลงาน Nature ปี 2022 แสดงว่าการค้นหาเชิงคำนวณช่วยค้นพบวิธีที่มนุษย์อาจไม่พบง่าย ๆ ตารางนี้อธิบายแนวคิด ไม่ใช่การสาธิตอัลกอริทึมจริง',['tensor'],'push'),
  make('06.02','จากลำดับ\nสู่โครงสร้าง','ออกแบบและทำนายโปรตีน · โนเบลเคมี 2024','protein','AI','A SCIENTIFIC BREAKTHROUGH','AI: โนเบลเคมีปี 2024 แบ่งระหว่าง David Baker ด้านออกแบบโปรตีน และ Demis Hassabis กับ John Jumper ด้านทำนายโครงสร้าง เอกสารรางวัลกล่าวถึง AlphaFold2 ต้องแยกจาก AlphaFold3 ที่เป็นงานอีกชิ้น ภาพสายโมเลกุลนี้เป็นภาพอธิบาย ไม่ใช่ข้อมูลโครงสร้างของโปรตีนจริง',['nobel'],'arc'),
  make('06.03','โลกจริง\nไม่ใช่โจทย์ปิด','บริบท · เป้าหมาย · ผู้คน','strategy','Human','BEYOND THE EQUATION','Human: เมื่อโจทย์เปลี่ยนจากคำนวณเป็นการตัดสินใจ เราต้องรู้บริบท เป้าหมาย และผลกระทบต่อผู้คน ความสำเร็จในโจทย์หนึ่งจึงไม่รับประกันโจทย์ข้างเคียง คิวนี้เป็นกรอบอธิบาย ไม่อ้างงาน Brookins ที่ยังไม่ได้ยืนยัน'),
  make('06.04','ความเก่ง\nไม่ได้เป็นเส้นตรง','The Jagged Technological Frontier','frontier','Human','A SMALL STEP CAN CROSS THE BOUNDARY','Human: งานกับที่ปรึกษา BCG 758 คนเสนอภาพขอบเขตความสามารถที่หยัก ไม่ใช่เส้นตรง บางงาน AI ช่วยมาก งานที่ดูใกล้เคียงกันอาจอยู่อีกฝั่งของขอบเขต รูปหน้าผาเป็นแผนภาพเชิงแนวคิด ไม่ใช่กราฟค่าประสิทธิภาพที่วัดตามแกนนี้',['frontier'],'dolly'),
  make('06.05','ในขอบเขต\nช่วยได้มาก','ระบุให้ชัดว่า “ดีขึ้น” วัดอะไร','frontier-data','Human','QUALITY ≠ SPEED','Human: ใน working paper ปี 2023 ที่สถาบันผู้วิจัยสรุปไว้ งานในขอบเขตมีคุณภาพจากผู้ประเมินสูงขึ้นกว่า 40% ทำงานเร็วขึ้นกว่า 25% และทำงานเสร็จมากขึ้นกว่า 12% ตัวเลขเหล่านี้คนละตัวชี้วัด ห้ามพูดว่าเร็วขึ้น 40% ผลนอกขอบเขตต้องพิจารณาโจทย์และฉบับงานวิจัย ไม่ใช้เป็นค่าการพังสากล',['frontier'],'punch')
 ]},
 {id:'07',title:'CONFIDENCE',start:1320,end:1555,cues:[
  hold('07.01','DEATH CAP\nROULETTE','GAME 04 · เชื่อแล้วรอด / เชื่อผิดตกรอบ',"สถานการณ์จำลอง 6 ด่าน ให้เลือกเชื่อหรือไม่เชื่อใน 4 วินาที เชื่อถูกได้ 300 ไม่เชื่อข้อผิดได้ 100 เชื่อผิดตาย ตกรอบและคะแนนเฉพาะเกมนี้เป็น 0 ผู้ตายดูต่อและกลับเล่นเกม 5 ได้ ไม่ตอบรอดได้ 0 ไม่อ้างผู้เสียชีวิตจริงหรือผลจำแนกเห็ดจาก AI เกจความมั่นใจเป็นค่าจำลอง"),
  make('07.02','มั่นใจมาก\nไม่ได้แปลว่าถูก','Confidence ≠ Correctness','mushroom','Human','99.8% CAN STILL BE THE WRONG ANSWER','Human: ภาพนี้เป็นเห็ด Amanita phalloides ส่วนเกจ 99.8% เป็นค่าที่สร้างสำหรับสถานการณ์จำลอง ไม่ใช่ผลระบุชนิดเห็ดจากระบบจริง น้ำเสียงและตัวเลขความมั่นใจไม่แทนหลักฐาน อย่าใช้ภาพนี้หรือแชตบอตตัดสินใจกินเห็ดป่า เรากำลังเรียนรู้เรื่องการตรวจคำตอบ ไม่ได้ฝึกระบุเห็ด',['mushroom'],'dolly')
 ]},
 {id:'08',title:'ACT 2 RESULTS',start:1555,end:1560,cues:[hold('08.01','SURVIVOR RANKINGS','ACT 02 · สรุปอันดับ','คิวคะแนน 5 วินาที ผู้ควบคุมเปลี่ยนตามผู้พูด ไม่แสดงผลผู้ชนะที่แต่งขึ้น')]},
 {id:'09',title:'EMPATHY',start:1560,end:1830,cues:[
  make('09.01','ฟังดูอบอุ่น\nแล้วเชื่อใจได้ไหม?','The Illusion of Empathy','chat','AI','WORDS THAT FEEL HUMAN','AI: ข้อความที่สุภาพและรับฟังสามารถทำให้ผู้ใช้รู้สึกสบายใจ ตัวอย่างบนจอเขียนขึ้นเพื่ออธิบายการสื่อสาร ไม่ใช่คำแนะนำรักษา เราต้องถามต่อว่าความรู้สึกจากข้อความเท่ากับคุณภาพการดูแลในโลกจริงหรือไม่'),
  make('09.02','คำตอบที่\nผู้ประเมินเลือก','78.6% เลือกคำตอบ chatbot ในงาน Ayers','empathy','AI','PERCEIVED QUALITY & EMPATHY','AI: Ayers และคณะใช้คำถาม 195 ข้อ ผู้เชี่ยวชาญสุขภาพประเมินคำตอบรวม 585 ครั้ง และเลือก chatbot 78.6% ของการประเมิน นี่คือการประเมินข้อความ ไม่ใช่คนไข้ลงคะแนน และไม่ใช่ผลการรักษา เรารับผลเรื่องการสื่อสารได้พร้อมกับรักษาขอบเขตของข้อสรุป',['ayers'],'punch'),
  make('09.03','ข้อความที่อบอุ่น\nยังต้องตรวจสอบ','การรับรู้ความเห็นอกเห็นใจ ≠ ผลการดูแล','tokens','Human','LANGUAGE. CONTEXT. CONSEQUENCES.','Human: งานประเมินข้อความไม่ได้พิสูจน์ว่าระบบมีความรู้สึก หรือสามารถรับผิดชอบการดูแล ผู้ใช้ต้องพิจารณาบริบท ความเสี่ยง และการส่งต่อให้คนที่เหมาะสม การจำลอง next-token บนจออธิบายกลไกทางภาษาอย่างย่อ ไม่ใช่คำอธิบายครบทุกองค์ประกอบของ AI และไม่ใช้ข้ออ้าง Kask ที่ยังยืนยันไม่ได้',['ayers'],'arc')
 ]},
 {id:'10',title:'VERIFICATION',start:1830,end:2070,cues:[
  make('10.01','คำแนะนำที่ดี\nต้องดีในบริบทด้วย','Tessa · NEDA · ระบบที่ถูกระงับในปี 2023','tessa','Human','WHEN CONTEXT CHANGES THE RISK','Human: ในเดือนพฤษภาคม 2023 NEDA ระงับ Tessa หลังมีรายงานคำแนะนำเกี่ยวกับลดน้ำหนักที่อาจเป็นอันตรายในบริบทความผิดปกติการกิน รายงานร่วมสมัยมีคำชี้แจงจากองค์กร ไม่อ้างว่าเหตุเกิดปี 2024 หรือมีผู้เสียชีวิตจากบอตนี้ ข้อความบนจอเป็นสรุปกรณี ไม่ใช่ข้อความแชตต้นฉบับ',['tessa'],'push'),
  hold('10.02',"CHAT\nWHACK-A-MOLE","GAME 05 · ทุบแชตที่ควรหยุด","เล่น Chat Whack-a-Mole 25 วินาที แตะหยุดข้อความเสี่ยงและปล่อยข้อความช่วยเหลือ ข้อความเป็นสถานการณ์จำลอง ไม่ใช่แชตจริง จอฉายแสดงสถิติและคะแนนจากข้อมูลจริง ผู้จัดกดเริ่มและยืนยันผล"),
  make('10.03','ตรวจก่อน\nปล่อยคำตอบ','บริบท → ความเสี่ยง → ส่งต่อ','gate','Human','HUMAN VERIFICATION GATE','Human: การตรวจไม่ใช่แค่คำตอบฟังสุภาพหรือไม่ แต่ถามว่าคำตอบเหมาะกับคนนี้และสถานการณ์นี้หรือไม่ หากข้อมูลไม่พอหรือความเสี่ยงสูง ต้องหยุดและส่งต่อผู้เชี่ยวชาญ การอนุมัติเป็นขั้นตอนที่มีเจ้าของชัดเจน ไม่ใช่ปุ่มที่กดผ่านอัตโนมัติ')
 ]},
 {id:'11',title:'ACCOUNTABILITY',start:2070,end:2275,cues:[
  make('11.01','เมื่อคำตอบ\nสร้างความเสียหาย','Air Canada · ข้อมูลส่วนลดค่าโดยสาร','case','Human','MOFFATT v. AIR CANADA','Human: คดี Moffatt v. Air Canada ปี 2024 เกี่ยวกับข้อมูลส่วนลดค่าโดยสารกรณีสูญเสียสมาชิกครอบครัวจาก chatbot ที่ไม่ตรงนโยบาย คณะพิจารณาคดีให้สายการบินรับผิดจากการให้ข้อมูลผิดในกรณีนั้น เป็นคดีแพ่งเรื่องชดเชย ไม่ใช่คำพิพากษาจำคุกหรือกฎว่าทุกบริษัทรับผิดทุกอย่าง 100% ไม่ใช้คดี Google ในต้นฉบับที่ยังยืนยันไม่ได้',['court'],'arc'),
  hold('11.02',"COMPANY\nSHIELD","GAME 06 · ลากบริษัทบังลูกค้า","เล่น Company Shield 25 วินาที ลากบริษัทรับข้อความก่อนถึงลูกค้า 3 ช่อง ข้อความที่รับกลายเป็นงานให้บริษัทตรวจ จอฉายแสดงผลและคะแนนห้องจริง ผู้จัดกดเริ่มและยืนยันผล คดีที่เล่าเป็นบริบท ไม่ใช่คำตัดสินจำลอง"),
  make('11.03','AI IS A TOOL.\nNOT A SHIELD.','ความรับผิดต้องพิจารณาหน้าที่และข้อเท็จจริง','liability','Human','OWN THE DECISION','Human: ประโยคนี้เป็นข้อสรุปของผู้พูด ไม่ใช่คำอ้างตรงจากศาลทั่วโลก การใช้เครื่องมือไม่ได้ทำให้หน้าที่ของผู้ให้บริการหายไป แต่ผู้ใดรับผิดและรับผิดอย่างไรต้องพิจารณากฎหมาย บทบาท และข้อเท็จจริงของแต่ละกรณี',['court'],'punch')
 ]},
 {id:'12',title:'ACT 3 RESULTS',start:2275,end:2280,cues:[hold('12.01','THE FINAL SPRINT','ACT 03 · สรุปอันดับ','คิวคะแนน 5 วินาที ไม่สร้างคะแนนหรืออ้างว่าผู้นำห่างกันหลักสิบแต้มโดยไม่มีข้อมูลจริง')]},
 {id:'13',title:'SYNERGY',start:2280,end:2640,cues:[
  make('13.01','BETTER\nTOGETHER?','คน + AI ย่อมดีที่สุดเสมอ จริงหรือ?','synergy','Both','NOT ALWAYS','Human: Vaccaro และคณะรวม 106 การทดลองกับ 370 effect sizes โดยเฉลี่ยระบบคนร่วม AI ต่ำกว่าฝ่ายที่เก่งที่สุดระหว่างคนหรือ AI แต่เหนือกว่าคนอย่างเดียวโดยเฉลี่ย ผลแตกต่างตามงาน จึงไม่สรุปว่าการร่วมมือแย่กว่าคนอย่างเดียวเสมอ',['synergy'],'punch'),
  make('13.02','การร่วมมือ\nต้องออกแบบ','มอบงาน · ตรวจหลักฐาน · อนุมัติ','design','Human','DESIGN THE HANDOFF','Human: เราต้องรู้ว่างานส่วนไหนเหมาะกับ AI ใครตรวจด้วยหลักฐานอะไร และเมื่อไรต้องหยุด ผล meta-analysis ไม่ได้พิสูจน์ว่าทุกความล้มเหลวเกิดจากสมองขี้เกียจ ตัวอย่างนี้เป็นกระบวนการที่เราเสนอเพื่อจัดการความเสี่ยง ไม่ใช่สูตรที่รับประกันทุกสถานการณ์'),
  make('13.03','เร็วแค่ไหน\nก็ต้องตรวจก่อนปล่อย','CrowdStrike · 19 July 2024','outage','Human','VERIFICATION ARCHITECTS','Human: CrowdStrike ระบุว่า content configuration update ทำให้ Windows sensor เกิดปัญหาวงกว้างในวันที่ 19 กรกฎาคม 2024 ใช้เป็นบทเรียนเรื่องการทดสอบและปล่อยระบบ เราไม่มีหลักฐานว่า generative AI เขียน update นี้ จึงไม่กล่าวเช่นนั้น บทบาทผู้ตรวจระบบยังสำคัญเมื่อเครื่องมือช่วยผลิตงานเร็วขึ้น',['crowdstrike'],'push'),
  make('13.04','HUMAN\nOVERSIGHT','กำกับดูแลให้เหมาะกับความเสี่ยง','oversight','Human','HIGH-RISK AI · ARTICLE 14','Human: Article 14 ของ EU AI Act กล่าวถึง human oversight สำหรับระบบ AI ความเสี่ยงสูง ข้อกำหนดขึ้นกับประเภทระบบ บทบาท และบทบัญญัติที่ใช้ ไม่ใช่ทุกระบบต้องมีคนกดอนุมัติทุกคำตอบ เราจะใช้หลักคิดว่าการกำกับต้องมีอำนาจและข้อมูลที่พอจะหยุดหรือแก้ระบบได้',['oversight'],'arc')
 ]},
 {id:'14',title:'SHARED CONTROL',start:2640,end:2820,cues:[hold('14.01',"MISSING\nPIECE","GAME 07 · AI เริ่ม คนเติม","AI เตรียมภาพฐาน ผู้เล่นทุกคนวาดต่อและส่งตรวจ จากนั้นสมาชิกเลือกตัวแทนกลุ่มและโหวตผลงานข้ามกลุ่ม จอฉายแสดงงานที่อนุมัติและผลคะแนนจริง ผู้จัดตรวจและกดเริ่มแต่ละช่วง ก่อนกดยืนยันผลไปต่อ")]},
 {id:'15',title:'SHARED FUTURE',start:2820,end:2910,cues:[
  make('15.01','สมการของ\nความรับผิดชอบ','เสนอ → ตรวจสอบ → รับผิดชอบ','formula','Both','THE FUTURE NEEDS A HUMAN SIGNATURE','Both: AI มีหน้าที่เสนอ มนุษย์มีหน้าที่ตรวจสอบ และมนุษย์กับองค์กรต้องรับผิดตามบทบาทและกฎหมาย สมการนี้เป็นหลักปฏิบัติของการนำเสนอ ไม่ใช่บทกฎหมายที่ใช้แทนรายละเอียดทุกกรณี',[],'push'),
  make('15.02','DIFFERENT\nMINDS.','สติปัญญาต่างลักษณะ','different','AI','THE FIRST PART OF THE PROMISE','AI: ฉันช่วยสะท้อนและจัดรูปแบบความรู้ เสนอทางเลือก และช่วยคำนวณได้ แต่ความหมายของทางเลือกต้องดูชีวิตและบริบทของคน เรามีสติปัญญาต่างลักษณะ'),
  make('15.03','SHARED\nFUTURE.','ก้าวสู่อนาคตร่วมกัน','future','Human','THE SECOND PART OF THE PROMISE','Human: เราสร้างอนาคตร่วมกันได้เมื่อเลือกใช้ความสามารถแต่ละฝ่ายอย่างเหมาะสม ตั้งคำถาม และตรวจคำตอบ การร่วมมือไม่เกิดจากการรวมเครื่องมือเฉย ๆ แต่เกิดจากการออกแบบหน้าที่และความไว้ใจที่ตรวจสอบได้',[],'arc'),
  make('15.04','HUMAN\nRESPONSIBILITY.','ผู้ตัดสินใจต้องพร้อมรับผิดชอบผลลัพธ์','responsibility','Both','THE PART WE MUST KEEP','Both: สติปัญญาต่างลักษณะ ก้าวสู่อนาคตร่วมกัน โดยมีความรับผิดชอบของมนุษย์เป็นแกนกลาง ความเร็วในการเสนอทางเลือกมีประโยชน์ เมื่อเรารู้ว่าใครตรวจ ใครตัดสินใจ และใครรับผลของการตัดสินใจนั้น',[],'punch')
 ]},
 {id:'16',title:'EPILOGUE',start:2910,end:3000,cues:[
  hold('16.01','GRAND PODIUM\nCEREMONY','ประกาศรางวัล · อันดับ 1–3','ผู้จัดประกาศผลจริงและเชิญตัวแทนรับรางวัล จอนี้เป็นข้อความ ไม่มีชื่อผู้ชนะหรือคะแนนสมมติ'),
  make('16.02','ตรวจก่อนเชื่อ','ชื่อของคุณยังอยู่บนงานนี้','thanks','Both','DIFFERENT MINDS. SHARED FUTURE. HUMAN RESPONSIBILITY.','Human: เมื่อใช้ AI ช่วยทำงาน อย่าลืมตรวจคำตอบและพิจารณาผลกระทบ งานที่ส่งและการตัดสินใจที่ทำยังมีชื่อและหน้าที่ของเรา ขอบคุณทุกคนครับ ผู้ควบคุมกด B เมื่อต้องการ fade ปิดจอ',[],'fade')
 ]}
];
export const allCues=chapters.flatMap((chapter,scene)=>chapter.cues.map((cue,beat)=>({scene,beat,chapter,cue})));
export function formatTime(s:number){return `${Math.floor(s/60).toString().padStart(2,'0')}:${(s%60).toString().padStart(2,'0')}`;}
